### ISSUE TITLE
Issues with existing control sequences

### ISSUE THREAD

**Issue by VegaDeftwing** [aurora-0025/gradient-terminal#2]
![image](https://user-images.githubusercontent.com/11283620/169075850-5cb7314f-78d6-4820-ac9d-377389f02360.png)

Notice how the bold control sequence characters get printed instead of making the text bold when using gterm

**Comment by aurora-0025** [comment]
I am aware of this issue but as im a newbie, I need some help to fix this issue

**Comment by VegaDeftwing** [comment]
it looks like the only "special" character you're handling is space:

```js
for (var ele of text) {
    if (ele != " ") {
      let r = Math.round(rgb[val][0]);
      let g = Math.round(rgb[val][1]);
      let b = Math.round(rgb[val][2]);
      out.push(`\x1b[38;2;${r};${g};${b}m${ele}\x1b[0m`);
      val += 1;
    } else {
      out.push(" ");
      val += 1;
    }
  }
  out = out.join("");
```

you could use a regular expression to check for ANSI control sequences
`/(\x9B|\x1B\[)[0-?]*[ -\/]*[@-~]/`

and on those make sure the input is echo'd back out - just make sure not to increment the gradient count (`val`) on match

I'd write up a patch, but I'm both not fluent in .js and think working though it if you're a newbie could be valuable.

If you're looking for some deeper knowledge on how the terminal actually works and what escape sequences even are you may want to read up on [Anatomy of a Terminal Emulator (Aram Drevekein)](https://www.poor.dev/blog/terminal-anatomy/). Then, you may want to read up on the actual character sequences, see [everything you ever wanted to know about terminals (Lexi Summer Hale)](http://xn--rpa.cc/irl/term.html) and [XTerm Control Sequences (Edward Moy)](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html).

By no means do I think all of that is necessary, just thought you may appreciate the extra reading material.

**Comment by aurora-0025** [comment]
> it looks like the only "special" character you're handling is space:
> 
> ```js
> for (var ele of text) {
>     if (ele != " ") {
>       let r = Math.round(rgb[val][0]);
>       let g = Math.round(rgb[val][1]);
>       let b = Math.round(rgb[val][2]);
>       out.push(`\x1b[38;2;${r};${g};${b}m${ele}\x1b[0m`);
>       val += 1;
>     } else {
>       out.push(" ");
>       val += 1;
>     }
>   }
>   out = out.join("");
> ```
> 
> you could use a regular expression to check for ANSI control sequences `/(\x9B|\x1B\[)[0-?]*[ -\/]*[@-~]/`
> 
> and on those make sure the input is echo'd back out - just make sure not to increment the gradient count (`val`) on match
> 
> I'd write up a patch, but I'm both not fluent in .js and think working though it if you're a newbie could be valuable.
> 
> If you're looking for some deeper knowledge on how the terminal actually works and what escape sequences even are you may want to read up on [Anatomy of a Terminal Emulator (Aram Drevekein)](https://www.poor.dev/blog/terminal-anatomy/). Then, you may want to read up on the actual character sequences, see [everything you ever wanted to know about terminals (Lexi Summer Hale)](http://xn--rpa.cc/irl/term.html) and [XTerm Control Sequences (Edward Moy)](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html).
> 
> By no means do I think all of that is necessary, just thought you may appreciate the extra reading material.

Thank You for providing the resources Ill look into it and Ill work on handling the ANSI control sequences 😊

**Comment by aurora-0025** [comment]
Yo I fixed it😁. I took so long as I was very busy but nevertheless, I learned a lot about Terminal Emulator and Regex thanks to you. 
![image](https://user-images.githubusercontent.com/78461388/190899959-fb85ebe0-c128-4cc7-bdd0-f73bbec4779f.png)
![image](https://user-images.githubusercontent.com/78461388/190900127-0bd699fa-6405-4597-aa66-60e78077c91c.png)
Now I made it to show the styling along with the colors
